[NC-296] CI/CD JIB 적용
colosseumcoinckr/backend-sample pull request #2
Opened 2024-06-21 05:47 UTC by Junseo-Mo

## Context

- Jira: [NC-296](https://colosseum.atlassian.net/browse/NC-296?atlOrigin=eyJpIjoiZmFmYTMzZGIyZTUyNGNiZTg5MTI3MzViNThiZWY4YzkiLCJwIjoiaiJ9)
- Confluence:
- Figma:

## Changes

- JIB Extension 은 아직 개발에 대한 Detail 이 정해지지 않았기 때문에 기본적인 것들만 추가
- Add 5 Yaml files
  - About PR onto 'develop' branch
  - About PR onto 'staging' branch
  - Yaml file about Deploy into 'alpha' server
  - Yaml file about  Deploy into 'staging(temp)' server
  - Yaml file about Release into 'production(temp)' server

## Impact

- Github action 을 사용하여 CI/CD 자동화 with JIB
- Git plan 이 적용되지 않았기 때문에 CD 관련 테스트는 불가, CI 만 개인프로젝트에서 완료
- **_CI/CD 테스트를 위해 Github secrets 추후 설정 필요 (권한 부여 또는 추가작업 필요)_**

## Testing

- CI 만 현재 테스트 가능, Deploy Full test 는 IAM, ECS, ECR 관련 세팅 및 설정 없이는 불가
- Deploy 는 Image push 직전까지 정상적으로 동작하는 것 확인 (Image build 까지)

2024-06-21 06:12 UTC, duho-lee requested changes

2024-06-21 06:12 UTC, duho-lee commented on .github/workflows/push-CD-production.yaml
> +      - name: Build, tag, and push image to Amazon ECR with JIB
tag, jib는 변경될 여지가 있네요.

Build & Push Image to AWS ECR 정도로는 어떨까요?
나머지 step도 이름이 긴데, 짧고 명확하게 나타낼 수는 없을까요?

2024-06-21 07:15 UTC, jaykingg commented on build.gradle.kts
> +                "-Duser.timezone=UTC",
> KST로 정책을 가져갈까합니다.

국내 사용자들만 있다면 상관없겠지만, 해외에서 2.0 서비스로 접속 시 잠재적 이슈가 있다고 생각합니다.
예를 들어 어떤 행사마감이 있다고 했을 때, KST 기준으로 한다면 시간 차가 많이 나는 대륙에서는 행사마감 시간을 정확, 신속하게 인지하지 못합니다.
UTC 를 사용하면 단순 계산만 하면되는 반면에 KST 사용 시 각 나라별 계산하는 법을 엔지니어가가 인지해야하며 서머타임을 적용하는 나라도 고려해야합니다.
따라서, App 과 Database 의 시간대를 일치시키고, 클라이언트에서 사용자 로컬 시간대로 변환하여 정확한 시간을 인지시키는 것이 효율적이라고 생각하는데, 어떻게 생각하시나요?

2024-06-21 07:54 UTC, jaykingg commented on build.gradle.kts
> +            "staging" -> mutableListOf(
done

2024-06-21 08:08 UTC, jaykingg commented on .github/workflows/push-CD-production.yaml
> +      - name: Build, tag, and push image to Amazon ECR with JIB
각 step 에서 오류가 발생하면, 무엇을 하다가 오류가 났는지 인지시키기 위해 주요 키워드들은 다 넣었습니다.
pipeline 에서 오류가 발생했을 때 보다 더 빠르게 찾아갈 수 있는 표지판이라고 생각해요
script 에는 길어 보일 수 있으나 실제 action 화면에서는 다음과 같이 나옵니다.🤔
![스크린샷 2024-06-21 오후 5 06 59](https://github.com/colosseumcoinckr/backend-sample/assets/20733918/65be725e-6af1-4287-b713-4e80f180f617)
![스크린샷 2024-06-21 오후 5 07 14](https://github.com/colosseumcoinckr/backend-sample/assets/20733918/b3f20903-dca5-429a-b016-39b7a36bb977)

2024-06-21 09:05 UTC, duho-lee requested changes

2024-06-21 09:05 UTC, duho-lee commented on .github/workflows/push-CD-alpha.yaml
> +        run: ./gradlew build
Multi Module이라 별도로 설정이 필요합니다.
build 에러 수정 부탁드려요~

2024-06-21 09:05 UTC, duho-lee commented on .github/workflows/push-CD-staging.yaml
> +          echo "shortCommitSha=$(git rev-parse --short ${{ github.sha }})" >>$GITHUB_OUTPUT
```suggestion
          echo "shortCommitSha=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_OUTPUT  
```

2024-06-24 04:28 UTC, duho-lee commented on build.gradle.kts
> +                "-Duser.timezone=UTC",
KST로 진행하는걸로 완료.

2024-06-24 04:30 UTC, duho-lee commented on .github/workflows/push-CD-production.yaml
> +      - name: Build, tag, and push image to Amazon ECR with JIB
별 중요한 내용은 아니니 다음에 고민해보아요 :D

2024-06-24 04:35 UTC, merged